[package]
name = "sysinfo-windows-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = { git = "https://github.com/jyuch/sysinfo.git", rev = "70f27afa1c6dda3d993371accad8f641bc52988d" }
# sysinfo = "0.27"
